Showable ratios
anttih/purescript-rationals pull request #27
Opened 2017-07-07 20:36 UTC by herrzinter

Moved the implementation for the show typeclass from Rational to Ratio, Rationals just call the show method on the wrapped Ratio. 
Ratios are now displayed with the '%' symbol as well as Rationals. If this is not wanted, as % is a constructor for the Rational, but not for the Ratio, I would nevertheless suggest to implement a simple show instance for Ratio.

2017-07-08 08:44 UTC, anttih commented
I think we should have Ratios show as `(Ratio x y)` since, as you say `%`, is not an operator on Ratios.

But, why not `newtype` your `Ratio` type?

2017-07-09 21:25 UTC, herrzinter commented
I just reverted the old commits, my first version actually showed `Ratio x y`.

It didn't seem neccessary to `newtype` my `Ratio`, but I'm not that experienced with FP, so maybe I'm missing something?

2017-07-11 09:06 UTC, anttih requested changes

2017-07-11 09:06 UTC, anttih commented on src/Data/Ratio.purs
> +  show (Ratio a b) = "Ratio " <> show a <> " " <> show b
Could you add parenthesis around this whole expression? It will be then safer to copy&paste this output into other expression.

2017-07-11 09:06 UTC, anttih commented
Wrapping in a `newtype` might not be neccessary but that would allow you to add custom type class instances, like `Show`.

2017-07-11 09:09 UTC, anttih commented
Oh, and could you squash the commits into just one?

2017-07-12 20:37 UTC, merged

2017-07-12 20:37 UTC, anttih commented
Thanks!